version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD-SHELL", "pgrep sqlservr > /dev/null" ]
      interval: 1s
      retries: 20
    networks:
      - bakemarket-net

  bakemarket-api:
    build:
      context: ./BakeMarket_DotNet
      dockerfile: BakeMarket.API/Dockerfile
      args:
        ENVIRONMENT: Production
    image: bakemarket-api
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "5000:8080"
    networks:
      - bakemarket-net

  bakemarket-nextjs:
    build:
      context: ./BakeMarket_Nextjs
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: "https://api.zanis.id.vn"
    image: bakemarket-nextjs
    depends_on:
      - bakemarket-api
    ports:
      - "3000:3000"
    networks:
      - bakemarket-net

networks:
  bakemarket-net:
    driver: bridge
