name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Thêm permissions này để cho phép GitHub Actions ghi vào repository
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o release --nologo

      # Thêm tệp .nojekyll để tránh việc GitHub Pages xử lý file như một trang Jekyll
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      # Nếu bạn sử dụng custom domain
      - name: Add CNAME file
        if: false  # Vô hiệu hóa bước này nếu bạn không sử dụng custom domain
        run: echo "yourdomain.com" > release/wwwroot/CNAME

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}  # Sử dụng token mặc định